package lime

//
// Use limetool to get data from Lime and store in local database
//
import (
	"fmt"
	"log/slog"

	"github.com/abundo/factum2/internal/jobevent"
	"github.com/abundo/factum2/internal/util"
	"github.com/abundo/factum2/models"
	"github.com/abundo/limetool"
	limetoolmodels "github.com/abundo/limetool/models"
	"gorm.io/gorm"
)

type Lime struct {
	ParamDB  *util.ConfigDB
	DB       *gorm.DB
	Limetool *limetool.Lime
}

func NewLime(PDB *util.ConfigDB) *Lime {
	lime := new(Lime)
	lime.ParamDB = PDB
	return lime
}

func GetMax(db *gorm.DB, column string) (uint, error) {
	var max uint
	err := db.Table("customers").Select("MAX(" + column + ")").Scan(&max).Error
	return max, err
}

// SaveCustomer upserts a customer matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row.
func (lime *Lime) SaveCustomer(row *models.Customer) error {
	var customer models.Customer
	res := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).Find(&customer)
	if res.RowsAffected > 0 {
		// Customer exists, update in place.
		row.ID = customer.ID
	}
	return lime.DB.Save(row).Error
}

// SaveDelivery upserts a service matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row.
//
// Lime never feeds ServiceType/BandwidthMbps/MaxMacAddresses, Fields,
// PseudowireID or L2VPNNetboxID - those are only ever set from the factum
// side. row only carries Lime-owned fields (including AgreementStatus), so
// carrying the previously-stored values of these forward onto row before
// the wholesale Save() below keeps a resync from silently wiping out that
// factum-added enrichment. service_endpoints is a separate table and is
// not touched by Save().
func (lime *Lime) SaveDelivery(row *models.Service) error {
	var delivery models.Service
	res := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).Find(&delivery)
	if res.RowsAffected > 0 {
		// Delivery exists, update in place.
		row.ID = delivery.ID
		row.ServiceType = delivery.ServiceType
		row.BandwidthMbps = delivery.BandwidthMbps
		row.MaxMacAddresses = delivery.MaxMacAddresses
		row.Fields = delivery.Fields
		row.PseudowireID = delivery.PseudowireID
		row.L2VPNNetboxID = delivery.L2VPNNetboxID
	}
	return lime.DB.Save(row).Error
}

// SaveContact upserts a contact matched by (source, source_id) rather than
// by factum ID - same reason as SaveCustomer. NotifyMaintenance is
// factum-owned (the operator toggle on the contacts page, including for
// Lime-synced rows) so a resync must not reset it; new Lime persons default
// it to true to match a manually created contact.
func (lime *Lime) SaveContact(row *models.Contact) error {
	var contact models.Contact
	res := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).Find(&contact)
	if res.RowsAffected > 0 {
		row.ID = contact.ID
		row.NotifyMaintenance = contact.NotifyMaintenance
	} else {
		row.NotifyMaintenance = true
	}
	return lime.DB.Save(row).Error
}

// replaceContactCustomers makes the Lime company the sole customer link for
// a Lime-synced contact. The GUI cannot edit those links (ApiContactCustomersPut
// rejects Source == "lime"), so wiping extras on resync cannot discard
// operator-added associations.
func (lime *Lime) replaceContactCustomers(contactID, customerID uint) error {
	return lime.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("contact_id = ?", contactID).Delete(&models.CustomerContact{}).Error; err != nil {
			return err
		}
		return tx.Create(&models.CustomerContact{ContactID: contactID, CustomerID: customerID}).Error
	})
}

func (lime *Lime) unlinkContactCustomer(contactID, customerID uint) error {
	return lime.DB.Where("contact_id = ? AND customer_id = ?", contactID, customerID).
		Delete(&models.CustomerContact{}).Error
}

func contactFromPerson(person limetoolmodels.LimePerson, lastSync uint) models.Contact {
	return models.Contact{
		Source:   "lime",
		SourceID: fmt.Sprintf("%d", person.ID),
		LastSync: lastSync,
		Name:     person.DisplayName(),
		Email:    person.Email,
		Phone:    person.PhoneNumber(),
	}
}

// serviceFromDelivery maps a Lime delivery (and its embedded agreement)
// onto a factum Service. AgreementStatus is Lime's agreement_status.text
// (e.g. "Active"); it stays empty when the delivery has no agreement or
// the agreement has no status, matching Product/Service which are also
// optional embedded relations.
func serviceFromDelivery(delivery limetoolmodels.LimeDelivery, customerID, lastSync uint) models.Service {
	d := models.Service{
		Source:     "lime",
		SourceID:   fmt.Sprintf("%d", delivery.ID),
		CustomerID: customerID,
		LastSync:   lastSync,
		ServiceID:  delivery.ConnectionNumber,
		Comment:    delivery.Comment,
	}
	if delivery.DeliveryPoint != nil {
		d.DeliveryPoint1 = delivery.DeliveryPoint.Address
	}
	if delivery.DeliveryPoint2 != nil {
		d.DeliveryPoint2 = delivery.DeliveryPoint2.Address
	}
	if delivery.Product != nil {
		d.Product = delivery.Product.Name
	}
	if delivery.Service != nil {
		d.Service = delivery.Service.Name
	}
	if delivery.Agreeement != nil && delivery.Agreeement.Status != nil {
		d.AgreementStatus = delivery.Agreeement.Status.Text
	}
	return d
}

// syncPerson writes an active Lime person as a factum contact linked to
// customer. Inactive persons are not created; if they were synced earlier,
// the customer link is removed so they drop off maintenance notify without
// deleting the contact row (and its send history).
func (lime *Lime) syncPerson(customer *models.Customer, person limetoolmodels.LimePerson, lastSync uint) error {
	if person.Inactive {
		var existing models.Contact
		res := lime.DB.Where("source = ? AND source_id = ?", "lime", fmt.Sprintf("%d", person.ID)).Find(&existing)
		if res.RowsAffected == 0 {
			return nil
		}
		return lime.unlinkContactCustomer(existing.ID, customer.ID)
	}

	row := contactFromPerson(person, lastSync)
	if err := lime.SaveContact(&row); err != nil {
		return err
	}
	return lime.replaceContactCustomers(row.ID, customer.ID)
}

// Fetch data from LIME, store in factum database
// If refresh is true, refresh data in cache
func (lime *Lime) SyncCustomers(companyNames []string, refresh bool, reporter jobevent.Reporter) error {
	var err error
	reporter.Emit(jobevent.Info, "Lime sync started")
	lime.DB, err = util.ConnectDatabase(lime.ParamDB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}

	// Lime credentials are database-backed (Settings, admin-editable in the
	// web UI) rather than in the YAML config file - see
	// util.GetOrCreateSettings.
	settings, err := util.GetOrCreateSettings(lime.DB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}
	lime.Limetool = limetool.NewLime(settings.LimeApiURL, settings.LimeApiToken)

	last_sync, err := GetMax(lime.DB, "last_sync")
	if err != nil {
		last_sync = 1
	}
	new_sync := last_sync + 1

	customerCount := 0
	contactCount := 0
	for _, companyName := range companyNames {
		companies, err := lime.Limetool.GetCompanies(companyName, refresh)
		if err != nil {
			reporter.EmitErr(err)
			return err
		}

		for _, company := range companies {
			slog.Debug("saving", "customer", company.Name)
			customerCount++
			var c models.Customer
			c.Source = "lime"
			c.SourceID = fmt.Sprintf("%d", company.ID)
			c.LastSync = new_sync
			c.Name = company.Name
			c.Postaladdress1 = company.Postaladdress1
			c.Postaladdress2 = company.Postaladdress2
			c.Postalcity = company.Postalcity
			c.Postalzipcode = company.Postalzipcode
			c.OrganizationNumber = company.Registrationno
			c.Country = company.Country

			err = lime.SaveCustomer(&c)
			if err != nil {
				reporter.EmitErr(err)
				return err
			}

			for _, delivery := range company.Deliveries {
				d := serviceFromDelivery(delivery, c.ID, new_sync)
				err = lime.SaveDelivery(&d)
				if err != nil {
					return err
				}
			}

			if err := lime.Limetool.GetPersons(company, refresh); err != nil {
				reporter.EmitErr(err)
				return err
			}
			for _, person := range company.Persons {
				if err := lime.syncPerson(&c, person, new_sync); err != nil {
					reporter.EmitErr(err)
					return err
				}
				if !person.Inactive {
					contactCount++
				}
			}
		}
	}

	reporter.Emit(jobevent.Info, "Lime sync: %d customer(s), %d contact(s) processed", customerCount, contactCount)
	return nil
}
