package lime

//
// Use limetool to get data from Lime and store in local database
//
import (
	"fmt"
	"log/slog"

	"github.com/abundo/factum2/internal/jobevent"
	"github.com/abundo/factum2/internal/util"
	"github.com/abundo/factum2/models"
	"github.com/abundo/limetool"
	"gorm.io/gorm"
)

type Lime struct {
	ParamDB  *util.ConfigDB
	DB       *gorm.DB
	Limetool *limetool.Lime
}

func NewLime(PDB *util.ConfigDB) *Lime {
	lime := new(Lime)
	lime.ParamDB = PDB
	return lime
}

func GetMax(db *gorm.DB, column string) (uint, error) {
	var max uint
	err := db.Table("customers").Select("MAX(" + column + ")").Scan(&max).Error
	return max, err
}

// SaveCustomer upserts a customer matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row.
func (lime *Lime) SaveCustomer(row *models.Customer) error {
	var customer models.Customer
	res := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).Find(&customer)
	if res.RowsAffected > 0 {
		// Customer exists, update in place.
		row.ID = customer.ID
	}
	return lime.DB.Save(row).Error
}

// SaveDelivery upserts a service matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row.
//
// Lime never feeds ServiceType/BandwidthMbps/MaxMacAddresses or the ELINE
// provisioning fields (Endpoint*/PseudowireID/L2VPNNetboxID) - those are
// only ever set from the factum side (the network GUI's service-type
// editor and ELINE provisioning flow, web/handler_service.go,
// web/handler_service_eline.go). row only carries Lime-owned fields, so
// carrying the previously-stored values of these forward onto row before
// the wholesale Save() below keeps a resync from silently wiping out that
// factum-added enrichment.
func (lime *Lime) SaveDelivery(row *models.Service) error {
	var delivery models.Service
	res := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).Find(&delivery)
	if res.RowsAffected > 0 {
		// Delivery exists, update in place.
		row.ID = delivery.ID
		row.ServiceType = delivery.ServiceType
		row.BandwidthMbps = delivery.BandwidthMbps
		row.MaxMacAddresses = delivery.MaxMacAddresses
		row.EndpointADeviceID = delivery.EndpointADeviceID
		row.EndpointAInterfaceID = delivery.EndpointAInterfaceID
		row.EndpointAVlan = delivery.EndpointAVlan
		row.EndpointASubinterfaceNetboxID = delivery.EndpointASubinterfaceNetboxID
		row.EndpointATerminationNetboxID = delivery.EndpointATerminationNetboxID
		row.EndpointBDeviceID = delivery.EndpointBDeviceID
		row.EndpointBInterfaceID = delivery.EndpointBInterfaceID
		row.EndpointBVlan = delivery.EndpointBVlan
		row.EndpointBSubinterfaceNetboxID = delivery.EndpointBSubinterfaceNetboxID
		row.EndpointBTerminationNetboxID = delivery.EndpointBTerminationNetboxID
		row.PseudowireID = delivery.PseudowireID
		row.L2VPNNetboxID = delivery.L2VPNNetboxID
	}
	return lime.DB.Save(row).Error
}

// Fetch data from LIME, store in factum database
// If refresh is true, refresh data in cache
func (lime *Lime) SyncCustomers(companyNames []string, refresh bool, reporter jobevent.Reporter) error {
	var err error
	reporter.Emit(jobevent.Info, "Lime sync started")
	lime.DB, err = util.ConnectMigrate(lime.ParamDB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}

	// Lime credentials are database-backed (Settings, admin-editable in the
	// web UI) rather than in the YAML config file - see
	// util.GetOrCreateSettings.
	settings, err := util.GetOrCreateSettings(lime.DB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}
	lime.Limetool = limetool.NewLime(settings.LimeApiURL, settings.LimeApiToken)

	last_sync, err := GetMax(lime.DB, "last_sync")
	if err != nil {
		last_sync = 1
	}
	new_sync := last_sync + 1

	customerCount := 0
	for _, companyName := range companyNames {
		companies, err := lime.Limetool.GetCompanies(companyName, refresh)
		if err != nil {
			reporter.EmitErr(err)
			return err
		}

		for _, company := range companies {
			slog.Debug("saving", "customer", company.Name)
			customerCount++
			var c models.Customer
			c.Source = "lime"
			c.SourceID = fmt.Sprintf("%d", company.ID)
			c.LastSync = new_sync
			c.Name = company.Name
			c.Postaladdress1 = company.Postaladdress1
			c.Postaladdress2 = company.Postaladdress2
			c.Postalcity = company.Postalcity
			c.Postalzipcode = company.Postalzipcode
			c.OrganizationNumber = company.Registrationno
			c.Country = company.Country

			err = lime.SaveCustomer(&c)
			if err != nil {
				reporter.EmitErr(err)
				return err
			}

			for _, delivery := range company.Deliveries {
				var d models.Service
				d.Source = "lime"
				d.SourceID = fmt.Sprintf("%d", delivery.ID)
				d.CustomerID = c.ID
				d.LastSync = new_sync
				d.ServiceID = delivery.ConnectionNumber
				d.Comment = delivery.Comment
				if delivery.DeliveryPoint != nil {
					d.DeliveryPoint1 = delivery.DeliveryPoint.Address
				}
				if delivery.DeliveryPoint2 != nil {
					d.DeliveryPoint2 = delivery.DeliveryPoint2.Address
				}
				if delivery.Product != nil {
					d.Product = delivery.Product.Name
				}
				if delivery.Service != nil {
					d.Service = delivery.Service.Name
				}
				err = lime.SaveDelivery(&d)
				if err != nil {
					return err
				}
			}

		}
	}

	reporter.Emit(jobevent.Info, "Lime sync: %d customer(s) processed", customerCount)
	return nil
}
