package lime

//
// Use limetool to get data from Lime and store in local database
//
import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/abundo/factum2/internal/cfgmgmt"
	"github.com/abundo/factum2/internal/jobevent"
	"github.com/abundo/factum2/internal/optical"
	"github.com/abundo/factum2/internal/util"
	"github.com/abundo/factum2/models"
	"github.com/abundo/limetool"
	limetoolmodels "github.com/abundo/limetool/models"
	"gorm.io/gorm"
)

type Lime struct {
	ParamDB  *util.ConfigDB
	DB       *gorm.DB
	Limetool *limetool.Lime
}

func NewLime(PDB *util.ConfigDB) *Lime {
	lime := new(Lime)
	lime.ParamDB = PDB
	return lime
}

func GetMax(db *gorm.DB, column string) (uint, error) {
	var max uint
	err := db.Table("customers").Select("MAX(" + column + ")").Scan(&max).Error
	return max, err
}

// SaveCustomer upserts a customer matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row. Lime-owned fields
// are copied onto the existing row so a resync does not zero CreatedAt
// (GORM Save writes the whole struct, including zero timestamps).
func (lime *Lime) SaveCustomer(row *models.Customer) error {
	var existing models.Customer
	err := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).First(&existing).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return lime.DB.Create(row).Error
	}
	if err != nil {
		return err
	}
	existing.LastSync = row.LastSync
	existing.Name = row.Name
	existing.Postaladdress1 = row.Postaladdress1
	existing.Postaladdress2 = row.Postaladdress2
	existing.Postalcity = row.Postalcity
	existing.Postalzipcode = row.Postalzipcode
	existing.OrganizationNumber = row.OrganizationNumber
	existing.Country = row.Country
	row.ID = existing.ID
	return lime.DB.Save(&existing).Error
}

// SaveDelivery upserts a service matched by (source, source_id) rather
// than by factum ID - the factum ID is autogenerated (see SyncCustomers)
// so it can't be used to find a previously-synced row.
//
// Lime never feeds ServiceType/BandwidthMbps/MaxMacAddresses, Fields,
// PseudowireID, L2VPNNetboxID or connection_type_id - those are only ever
// set from the factum side. Overlaying Lime-owned fields onto the stored
// row (instead of Save() of a fresh struct) keeps a resync from wiping
// that enrichment and from zeroing CreatedAt.
// service_endpoints is a separate table and is not touched.
func (lime *Lime) SaveDelivery(row *models.Service) error {
	var existing models.Service
	err := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).First(&existing).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return lime.DB.Create(row).Error
	}
	if err != nil {
		return err
	}
	existing.LastSync = row.LastSync
	existing.CustomerID = row.CustomerID
	existing.ServiceID = row.ServiceID
	existing.Comment = row.Comment
	existing.DeliveryPoint1 = row.DeliveryPoint1
	existing.DeliveryPoint2 = row.DeliveryPoint2
	existing.Product = row.Product
	existing.Service = row.Service
	existing.AgreementStatus = row.AgreementStatus
	row.ID = existing.ID
	return lime.DB.Save(&existing).Error
}

// SaveContact upserts a contact matched by (source, source_id) rather than
// by factum ID - same reason as SaveCustomer. NotifyMaintenance is
// factum-owned (the operator toggle on the contacts page, including for
// Lime-synced rows) so a resync must not reset it; new Lime persons default
// it to false so they are not mailed until an operator opts them in.
func (lime *Lime) SaveContact(row *models.Contact) error {
	var existing models.Contact
	err := lime.DB.Where("source = ? AND source_id = ?", row.Source, row.SourceID).First(&existing).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		row.NotifyMaintenance = false
		return lime.DB.Create(row).Error
	}
	if err != nil {
		return err
	}
	existing.LastSync = row.LastSync
	existing.Name = row.Name
	existing.Email = row.Email
	existing.Phone = row.Phone
	row.ID = existing.ID
	row.NotifyMaintenance = existing.NotifyMaintenance
	return lime.DB.Save(&existing).Error
}

// replaceContactCustomers makes the Lime company the sole customer link for
// a Lime-synced contact. The GUI cannot edit those links (ApiContactCustomersPut
// rejects Source == "lime"), so wiping extras on resync cannot discard
// operator-added associations.
func (lime *Lime) replaceContactCustomers(contactID, customerID uint) error {
	return lime.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("contact_id = ?", contactID).Delete(&models.CustomerContact{}).Error; err != nil {
			return err
		}
		return tx.Create(&models.CustomerContact{ContactID: contactID, CustomerID: customerID}).Error
	})
}

func (lime *Lime) unlinkContactCustomer(contactID, customerID uint) error {
	return lime.DB.Where("contact_id = ? AND customer_id = ?", contactID, customerID).
		Delete(&models.CustomerContact{}).Error
}

func contactFromPerson(person limetoolmodels.LimePerson, lastSync uint) models.Contact {
	return models.Contact{
		Source:   "lime",
		SourceID: fmt.Sprintf("%d", person.ID),
		LastSync: lastSync,
		Name:     person.DisplayName(),
		Email:    person.Email,
		Phone:    person.PhoneNumber(),
	}
}

// serviceFromDelivery maps a Lime delivery (and its embedded agreement)
// onto a factum Service. AgreementStatus is Lime's agreement_status.text
// (e.g. "Active"); it stays empty when the delivery has no agreement or
// the agreement has no status, matching Product/Service which are also
// optional embedded relations.
func serviceFromDelivery(delivery limetoolmodels.LimeDelivery, customerID, lastSync uint) models.Service {
	d := models.Service{
		Source:     "lime",
		SourceID:   fmt.Sprintf("%d", delivery.ID),
		CustomerID: customerID,
		LastSync:   lastSync,
		ServiceID:  delivery.ConnectionNumber,
		Comment:    delivery.Comment,
	}
	if delivery.DeliveryPoint != nil {
		d.DeliveryPoint1 = delivery.DeliveryPoint.Address
	}
	if delivery.DeliveryPoint2 != nil {
		d.DeliveryPoint2 = delivery.DeliveryPoint2.Address
	}
	if delivery.Product != nil {
		d.Product = delivery.Product.Name
	}
	if delivery.Service != nil {
		d.Service = delivery.Service.Name
	}
	if delivery.Agreeement != nil && delivery.Agreeement.Status != nil {
		d.AgreementStatus = delivery.Agreeement.Status.Text
	}
	return d
}

// syncPerson writes an active Lime person as a factum contact linked to
// customer. Inactive persons are not created; if they were synced earlier,
// the customer link is removed so they drop off maintenance notify without
// deleting the contact row (and its send history).
func (lime *Lime) syncPerson(customer *models.Customer, person limetoolmodels.LimePerson, lastSync uint) error {
	if person.Inactive {
		var existing models.Contact
		err := lime.DB.Where("source = ? AND source_id = ?", "lime", fmt.Sprintf("%d", person.ID)).First(&existing).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil
		}
		if err != nil {
			return err
		}
		return lime.unlinkContactCustomer(existing.ID, customer.ID)
	}

	row := contactFromPerson(person, lastSync)
	if err := lime.SaveContact(&row); err != nil {
		return err
	}
	return lime.replaceContactCustomers(row.ID, customer.ID)
}

// isFullLimeSync is true when GetCompanies is asked for every company
// (empty name). A filtered -c run must not delete other customers.
func isFullLimeSync(companyNames []string) bool {
	if len(companyNames) == 0 {
		return true
	}
	for _, n := range companyNames {
		if n == "" {
			return true
		}
	}
	return false
}

// deleteLimeService drops a Lime-synced service and the config-tree /
// optical / endpoint rows that point at it - same cleanup as
// ApiServiceDelete, without the GUI's Lime-source refusal.
func (lime *Lime) deleteLimeService(svc *models.Service) error {
	return lime.DB.Transaction(func(tx *gorm.DB) error {
		if err := cfgmgmt.DetachServiceByRowID(tx, svc.ID); err != nil {
			return err
		}
		if err := optical.DeletePathForService(tx, svc.ID); err != nil {
			return err
		}
		if err := tx.Where("service_id = ?", svc.ID).Delete(&models.ServiceEndpoint{}).Error; err != nil {
			return err
		}
		return tx.Delete(svc).Error
	})
}

// pruneStaleDeliveries removes Lime services for this customer that were
// not written this run (Lime no longer returned them). Factum-created
// services on the same customer are left alone.
func (lime *Lime) pruneStaleDeliveries(customerID, lastSync uint) (int64, error) {
	var stale []models.Service
	if err := lime.DB.Where("source = ? AND customer_id = ? AND last_sync < ?", "lime", customerID, lastSync).
		Find(&stale).Error; err != nil {
		return 0, err
	}
	var n int64
	for i := range stale {
		if err := lime.deleteLimeService(&stale[i]); err != nil {
			return n, err
		}
		n++
	}
	return n, nil
}

// pruneRemovedPersonLinks drops the customer-contact join for Lime persons
// that were not seen this run. Contact rows stay (send history), matching
// inactive persons which are unlinked rather than deleted.
func (lime *Lime) pruneRemovedPersonLinks(customerID, lastSync uint) (int64, error) {
	res := lime.DB.Exec(`
		DELETE FROM customer_contacts
		WHERE customer_id = ?
		  AND contact_id IN (
			SELECT id FROM contacts WHERE source = 'lime' AND last_sync < ?
		  )`, customerID, lastSync)
	return res.RowsAffected, res.Error
}

// pruneStaleCustomers removes Lime companies that a full sync did not see.
// Lime services on those companies are deleted first. A company that still
// has factum-created services is left in place so those rows keep a parent.
func (lime *Lime) pruneStaleCustomers(lastSync uint) (removedCustomers, removedServices int64, err error) {
	var stale []models.Customer
	if err := lime.DB.Where("source = ? AND last_sync < ?", "lime", lastSync).Find(&stale).Error; err != nil {
		return 0, 0, err
	}
	for i := range stale {
		c := &stale[i]
		var svcs []models.Service
		if err := lime.DB.Where("source = ? AND customer_id = ?", "lime", c.ID).Find(&svcs).Error; err != nil {
			return removedCustomers, removedServices, err
		}
		for j := range svcs {
			if err := lime.deleteLimeService(&svcs[j]); err != nil {
				return removedCustomers, removedServices, err
			}
			removedServices++
		}
		var remaining int64
		if err := lime.DB.Model(&models.Service{}).Where("customer_id = ?", c.ID).Count(&remaining).Error; err != nil {
			return removedCustomers, removedServices, err
		}
		if remaining > 0 {
			continue
		}
		if err := lime.DB.Where("customer_id = ?", c.ID).Delete(&models.CustomerContact{}).Error; err != nil {
			return removedCustomers, removedServices, err
		}
		if err := lime.DB.Delete(c).Error; err != nil {
			return removedCustomers, removedServices, err
		}
		removedCustomers++
	}
	return removedCustomers, removedServices, nil
}

// Fetch data from LIME, store in factum database
// If refresh is true, refresh data in cache
func (lime *Lime) SyncCustomers(companyNames []string, refresh bool, reporter jobevent.Reporter) error {
	var err error
	reporter.Emit(jobevent.Info, "Lime sync started")
	lime.DB, err = util.ConnectDatabase(lime.ParamDB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}

	// Lime credentials are database-backed (Settings, admin-editable in the
	// web UI) rather than in the YAML config file - see
	// util.GetOrCreateSettings.
	settings, err := util.GetOrCreateSettings(lime.DB)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}
	lime.Limetool = limetool.NewLime(settings.LimeApiURL, settings.LimeApiToken)

	last_sync, err := GetMax(lime.DB, "last_sync")
	if err != nil {
		last_sync = 1
	}
	new_sync := last_sync + 1
	fullSync := isFullLimeSync(companyNames)

	customerCount := 0
	contactCount := 0
	var prunedServices, prunedCustomers, prunedLinks int64
	for _, companyName := range companyNames {
		companies, err := lime.Limetool.GetCompanies(companyName, refresh)
		if err != nil {
			reporter.EmitErr(err)
			return err
		}

		for _, company := range companies {
			slog.Debug("saving", "customer", company.Name)
			customerCount++
			var c models.Customer
			c.Source = "lime"
			c.SourceID = fmt.Sprintf("%d", company.ID)
			c.LastSync = new_sync
			c.Name = company.Name
			c.Postaladdress1 = company.Postaladdress1
			c.Postaladdress2 = company.Postaladdress2
			c.Postalcity = company.Postalcity
			c.Postalzipcode = company.Postalzipcode
			c.OrganizationNumber = company.Registrationno
			c.Country = company.Country

			err = lime.SaveCustomer(&c)
			if err != nil {
				reporter.EmitErr(err)
				return err
			}

			for _, delivery := range company.Deliveries {
				d := serviceFromDelivery(delivery, c.ID, new_sync)
				err = lime.SaveDelivery(&d)
				if err != nil {
					return err
				}
			}

			if err := lime.Limetool.GetPersons(company, refresh); err != nil {
				reporter.EmitErr(err)
				return err
			}
			for _, person := range company.Persons {
				if err := lime.syncPerson(&c, person, new_sync); err != nil {
					reporter.EmitErr(err)
					return err
				}
				if !person.Inactive {
					contactCount++
				}
			}

			n, err := lime.pruneStaleDeliveries(c.ID, new_sync)
			if err != nil {
				reporter.EmitErr(err)
				return err
			}
			prunedServices += n
			n, err = lime.pruneRemovedPersonLinks(c.ID, new_sync)
			if err != nil {
				reporter.EmitErr(err)
				return err
			}
			prunedLinks += n
		}
	}

	if fullSync {
		removedCust, removedSvc, err := lime.pruneStaleCustomers(new_sync)
		if err != nil {
			reporter.EmitErr(err)
			return err
		}
		prunedCustomers += removedCust
		prunedServices += removedSvc
	}

	reporter.Emit(jobevent.Info, "Lime sync: %d customer(s), %d contact(s) processed; removed %d service(s), %d customer(s), %d contact link(s)",
		customerCount, contactCount, prunedServices, prunedCustomers, prunedLinks)
	return nil
}
