/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttachServiceDialog: typeof import('./src/components/AttachServiceDialog.vue')['default']
    BuildInfo: typeof import('./src/components/BuildInfo.vue')['default']
    ConfigNodeInspector: typeof import('./src/components/ConfigNodeInspector.vue')['default']
    ConfigScopeTree: typeof import('./src/components/ConfigScopeTree.vue')['default']
    DeviceInterfacePicker: typeof import('./src/components/DeviceInterfacePicker.vue')['default']
    FormModal: typeof import('./src/components/FormModal.vue')['default']
    GoTemplateEditor: typeof import('./src/components/GoTemplateEditor.vue')['default']
    GoTemplateField: typeof import('./src/components/GoTemplateField.vue')['default']
    HomogeneousInterfaces: typeof import('./src/components/HomogeneousInterfaces.vue')['default']
    IpamPrefixForm: typeof import('./src/components/IpamPrefixForm.vue')['default']
    IpamPrefixTree: typeof import('./src/components/IpamPrefixTree.vue')['default']
    LdapTreeBrowser: typeof import('./src/components/LdapTreeBrowser.vue')['default']
    OxidizedNodeDialog: typeof import('./src/components/OxidizedNodeDialog.vue')['default']
    OxidizedNodePanel: typeof import('./src/components/OxidizedNodePanel.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFieldControl: typeof import('./src/components/SchemaFieldControl.vue')['default']
    SchemaFields: typeof import('./src/components/SchemaFields.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ServiceEditDialog: typeof import('./src/components/ServiceEditDialog.vue')['default']
    ServiceTypeFieldEditor: typeof import('./src/components/ServiceTypeFieldEditor.vue')['default']
    SiteSelector: typeof import('./src/components/SiteSelector.vue')['default']
    SiteTree: typeof import('./src/components/SiteTree.vue')['default']
    SortableColumnHeader: typeof import('./src/components/SortableColumnHeader.vue')['default']
    TechnicalServiceForm: typeof import('./src/components/TechnicalServiceForm.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UContextMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    URadioGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UStepper: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    VlanEditDialog: typeof import('./src/components/VlanEditDialog.vue')['default']
    ZoneRecordsTable: typeof import('./src/components/ZoneRecordsTable.vue')['default']
  }
}
