package icinga

//
// Update icinga configuration
//

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/abundo/factum2/internal/factum"
	"github.com/abundo/factum2/internal/jobevent"
	"github.com/abundo/factum2/internal/util"
	"github.com/abundo/factum2/models"
)

type FactumIcingaClient struct {
	Config       *util.ConfigFactum
	IcingaConfig *util.ConfigIcinga
	Icinga       *icingaClient

	// Users collects alarm-destination email addresses seen while writing
	// hosts (writeDevices), for writeUsers to turn into Icinga User
	// objects. Reset at the start of each Update().
	Users map[string]bool
}

// NewFactumIcingaClient fetches the Icinga API connection settings and the
// icinga_sync config (hosts/users file paths, templates, ignore list, ...)
// from the primary over REST - config.Icinga is never used, since
// factum-icinga typically runs on a different host than the primary and has
// no local icinga config of its own (see util.ConfigIcinga's doc comment).
func NewFactumIcingaClient(config *util.ConfigFactum) (*FactumIcingaClient, error) {
	client := new(FactumIcingaClient)
	client.Config = config

	icingaConfig, err := FetchRemoteConfig(config)
	if err != nil {
		return nil, err
	}
	client.IcingaConfig = icingaConfig
	client.Icinga = NewIcingaClient(*icingaConfig)
	return client, nil
}

// createConfFile creates a new config file, with a warning header saying
// it's auto-generated and shouldn't be edited by hand.
func createConfFile(filename string, message string) (*os.File, error) {
	f, err := os.Create(filename)
	if err != nil {
		return nil, err
	}
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// Auto-generated by factum2. Note: do not edit this file, your changes will be overwritten/lost")
	if message != "" {
		fmt.Fprintf(f, "// %s\n", message)
	}
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f)
	return f, nil
}

// installConfFile installs tmpFile as dst, but only if its content differs
// from what's already there - this is what tells Update() whether icinga2
// actually needs a reload.
func installConfFile(tmpFile, dst string) (bool, error) {
	newContent, err := os.ReadFile(tmpFile)
	if err != nil {
		return false, err
	}
	oldContent, err := os.ReadFile(dst)
	if err == nil && bytes.Equal(oldContent, newContent) {
		os.Remove(tmpFile)
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := os.Rename(tmpFile, dst); err != nil {
		return false, err
	}
	return true, nil
}

// isIgnoredDevice reports whether name appears in ignoreDevices, a
// newline-separated list (Settings.IcingaIgnoreDevices).
func isIgnoredDevice(name, ignoreDevices string) bool {
	for _, ignored := range strings.Split(ignoreDevices, "\n") {
		if strings.TrimSpace(ignored) == name {
			return true
		}
	}
	return false
}

// hostTemplateFuncs are the custom functions available inside
// Settings.IcingaHostTemplate. defaultDomain is Settings.DefaultDomain,
// used by "fqdn" to qualify bare device names.
func hostTemplateFuncs(defaultDomain string) template.FuncMap {
	return template.FuncMap{
		// ip strips the "/prefixlen" suffix from a CIDR address (e.g.
		// models.Device.PrimaryIPv4, which is stored as "10.0.0.1/24"),
		// returning just the address.
		"ip": func(cidr string) string {
			return strings.Split(cidr, "/")[0]
		},
		// fqdn appends defaultDomain to name if it has no "." in it
		// already - icinga2 host object names must be FQDNs, but
		// factum device names aren't always stored fully qualified.
		"fqdn": func(name string) string {
			if strings.Contains(name, ".") || defaultDomain == "" {
				return name
			}
			return name + "." + defaultDomain
		},
	}
}

// hostTemplateData is what Settings.IcingaHostTemplate is executed with, one
// per device.
type hostTemplateData struct {
	Device  *models.Device
	Options string // pre-built "vars.pe_xxx = ..." lines, already newline-joined
}

// writeDevices renders one Icinga Host object per enabled, monitored device
// into IcingaConfig.HostsFile (Settings.IcingaHostTemplate), and collects
// each device's alarm destination into fic.Users for writeUsers.
//
// Dependency objects (Settings.IcingaDependencyTemplate) aren't rendered:
// models.Device has no Parents field to build them from -
// internal/librenms hit the same gap and skipped parent sync for the same
// reason, see factum-librenms.go.
func (fic *FactumIcingaClient) writeDevices(devices []*models.Device, reporter jobevent.Reporter) (bool, error) {
	hostTmpl, err := template.New("host").Funcs(hostTemplateFuncs(fic.IcingaConfig.DefaultDomain)).Parse(fic.IcingaConfig.HostTemplate)
	if err != nil {
		return false, fmt.Errorf("parsing icinga host template: %w", err)
	}

	tmpFile := fic.IcingaConfig.HostsFile + ".tmp"
	f, err := createConfFile(tmpFile, fmt.Sprintf("%d hosts", len(devices)))
	if err != nil {
		return false, err
	}

	written := 0
	for _, device := range devices {
		if isIgnoredDevice(device.Name, fic.IcingaConfig.IgnoreDevices) {
			continue
		}
		if !device.Enabled {
			// reporter.Emit(jobevent.Warning, "Ignoring %s, device is not enabled", device.Name)
			continue
		}
		if device.PrimaryIPv4 == "" {
			// reporter.Emit(jobevent.Warning, "Ignoring device %q, no primary_ip4", device.Name)
			continue
		}

		var options []string
		if device.CfAlarmDestination != "" {
			options = append(options, fmt.Sprintf("  vars.factum_alarm_destination = [ \"%s\" ]", quote(device.CfAlarmDestination)))
			fic.Users[device.CfAlarmDestination] = true
		} else if fic.IcingaConfig.DefaultNotification != "" {
			options = append(options, fic.IcingaConfig.DefaultNotification)
		}
		if device.CfAlarmTimeperiod != "" {
			options = append(options, fmt.Sprintf("  vars.factum_alarm_timeperiod = \"%s\"", quote(device.CfAlarmTimeperiod)))
		}
		if device.CfBackupOxidized {
			options = append(options, "  vars.pe_backup_oxidized = true")
		}

		device.Comments = quote(device.Comments) // uglyqq

		data := hostTemplateData{
			Device:  device,
			Options: strings.Join(options, "\n"),
		}
		if err := hostTmpl.Execute(f, data); err != nil {
			f.Close()
			return false, fmt.Errorf("rendering icinga host template for %q: %w", device.Name, err)
		}
		written++
	}

	if err := f.Close(); err != nil {
		return false, err
	}
	reporter.Emit(jobevent.Info, "wrote %d host(s) to %s", written, fic.IcingaConfig.HostsFile)
	return installConfFile(tmpFile, fic.IcingaConfig.HostsFile)
}

// userTemplateData is what Settings.IcingaUserTemplate is executed with, one
// per alarm-destination email address collected by writeDevices.
type userTemplateData struct {
	Username    string
	DisplayName string
	Email       string
}

// writeUsers renders one Icinga User object per email destination collected
// by writeDevices into IcingaConfig.UsersFile (Settings.IcingaUserTemplate).
func (fic *FactumIcingaClient) writeUsers(reporter jobevent.Reporter) (bool, error) {
	userTmpl, err := template.New("user").Parse(fic.IcingaConfig.UserTemplate)
	if err != nil {
		return false, fmt.Errorf("parsing icinga user template: %w", err)
	}

	tmpFile := fic.IcingaConfig.UsersFile + ".tmp"
	f, err := createConfFile(tmpFile, "")
	if err != nil {
		return false, err
	}

	// Sort so the generated file has a stable order - fic.Users is a map,
	// and an unstable order would make installConfFile see a "change"
	// every run even when nothing actually changed.
	destinations := make([]string, 0, len(fic.Users))
	for destination := range fic.Users {
		destinations = append(destinations, destination)
	}
	sort.Strings(destinations)

	for _, destination := range destinations {
		data := userTemplateData{
			Username:    destination,
			DisplayName: destination,
			Email:       destination,
		}
		if err := userTmpl.Execute(f, data); err != nil {
			f.Close()
			return false, fmt.Errorf("rendering icinga user template for %q: %w", destination, err)
		}
	}

	if err := f.Close(); err != nil {
		return false, err
	}
	reporter.Emit(jobevent.Info, "wrote %d user(s) to %s", len(destinations), fic.IcingaConfig.UsersFile)
	return installConfFile(tmpFile, fic.IcingaConfig.UsersFile)
}

// Sync fetches devices from the Factum API, writes the icinga2 hosts and
// users config files, and asks icinga2 to reload if anything changed.
func (fic *FactumIcingaClient) Sync(reporter jobevent.Reporter) error {
	reporter.Emit(jobevent.Info, "Icinga sync started")
	factumClient := factum.NewFactumClient(fic.Config)
	allDevices, err := factumClient.GetDevices()
	if err != nil {
		reporter.EmitErr(err)
		return err
	}

	var devices []*models.Device
	for _, device := range allDevices {
		if !device.CfMonitorIcinga {
			continue
		}
		devices = append(devices, device)
	}

	fic.Users = make(map[string]bool)

	hostsChanged, err := fic.writeDevices(devices, reporter)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}
	usersChanged, err := fic.writeUsers(reporter)
	if err != nil {
		reporter.EmitErr(err)
		return err
	}

	if hostsChanged || usersChanged {
		reporter.Emit(jobevent.Info, "Asking icinga to reload configuration")
		if _, err := fic.Icinga.Reload(); err != nil {
			reporter.EmitErr(err)
			return err
		}
	} else {
		reporter.Emit(jobevent.Info, "No change in icinga configuration")
	}
	return nil
}
