package web

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"html/template"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/abundo/factum2/internal/ldapauth"
	"github.com/abundo/factum2/internal/mail"
	"github.com/abundo/factum2/internal/util"
	"github.com/abundo/factum2/models"
	"github.com/labstack/echo/v5"
	"gorm.io/gorm"
)

// --------------------------------------------------------------------------
//
// # Forgot / reset password
//
// Two-endpoint flow: ApiForgotPassword emails a link (long random token,
// redeemed via ?token=) and a short human-typeable code (redeemed via
// email+code) - either one completes the reset, both point at the same
// models.PasswordResetToken row. Neither endpoint requires auth, both are
// deliberately vague about whether an account exists to avoid user
// enumeration - see ApiForgotPassword's doc comment.
//
// --------------------------------------------------------------------------

const (
	passwordResetTokenTTL        = 30 * time.Minute
	passwordResetCooldown        = 30 * time.Second
	passwordResetMaxCodeAttempts = 10
	minPasswordLength            = 8
)

// hashToken deterministically hashes a token or code for storage/lookup.
// Both are generated by crypto/rand, not user-chosen, so a fast hash is
// fine here - bcrypt's slow-hash property exists to blunt dictionary
// attacks on human-chosen secrets, which doesn't apply to a random value
// drawn from a keyspace no dictionary is smaller than.
func hashToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])
}

// generateResetToken returns a high-entropy token for the emailed link.
func generateResetToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// generateResetCode returns a short human-typeable numeric code. Low
// entropy compared to the link token, so it's only ever looked up scoped
// to one user (by email) with an attempt limit - see resolveResetToken.
func generateResetCode() (string, error) {
	const digits = "0123456789"
	raw := make([]byte, 8)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	code := make([]byte, len(raw))
	for i, v := range raw {
		code[i] = digits[int(v)%len(digits)]
	}
	return string(code), nil
}

// ldapWritebackAvailable reports whether an LDAP-backed user's password can
// actually be changed: LDAP auth must be on, the admin-visible
// LdapAllowPasswordChange toggle must be on, AND the elevated write-back
// identity must be configured - that last part lives only in
// util.Config.LdapWriteback (YAML config file), never in Settings/the DB,
// so an admin turning the toggle on without an operator also setting the
// config file still fails closed here rather than silently no-opping.
func ldapWritebackAvailable(settings *models.Settings) bool {
	return settings.LdapEnabled != nil && *settings.LdapEnabled &&
		settings.LdapAllowPasswordChange != nil && *settings.LdapAllowPasswordChange &&
		util.Config.LdapWriteback.BindDN != ""
}

// provisionLDAPUserByEmail searches LDAP for an entry matching email and,
// if found, auto-provisions a local sentinel User row for it - the same
// shape authenticateNewLDAPUser (web/auth.go) creates on a first successful
// login, just triggered here by an unauthenticated forgot-password request
// instead of a verified credential. That's safe: the row alone grants no
// access (logging in still requires the real LDAP password), it just lets
// a directory user who has never logged in yet actually receive a reset
// email or the "contact your administrator" notice. Returns (nil, nil) if
// LDAP is disabled, no entry matches, or AttrUsername/AttrEmail aren't
// configured - same "not an error, just nothing to do" contract as
// ldapauth.LookupByEmail.
func (ctrl *Controller) provisionLDAPUserByEmail(settings *models.Settings, email string) (*models.User, error) {
	if settings.LdapEnabled == nil || !*settings.LdapEnabled {
		return nil, nil
	}

	cfg := ldapauth.ConfigFromSettings(settings)
	info, err := ldapauth.LookupByEmail(cfg, email)
	if err != nil {
		return nil, err
	}
	if info == nil {
		return nil, nil
	}

	// A concurrent login (or an earlier forgot-password request racing
	// this one) may have already provisioned this exact user between the
	// caller's email lookup and here - re-check by username, the actual
	// uniqueness key (models.User.Username is uniqueIndex; Email isn't).
	var existing models.User
	if err := ctrl.DB.Where("username = ?", info.Username).First(&existing).Error; err == nil {
		return &existing, nil
	}

	name := info.DisplayName
	if name == "" {
		name = info.Username
	}
	user := models.User{
		Username:     info.Username,
		PasswordHash: ldapSentinelPassword,
		Name:         name,
		Email:        info.Email,
		Mobile:       info.Mobile,
	}
	if err := ctrl.DB.Create(&user).Error; err != nil {
		return nil, err
	}
	if err := syncLDAPRoles(ctrl.DB, &user, settings, info.Groups); err != nil {
		return nil, err
	}
	return &user, nil
}

// publicBaseURL is the origin used to build the reset link - prefers the
// admin-configured Settings.PublicBaseURL, falling back to the incoming
// request's scheme+Host for simple setups that haven't set it.
func publicBaseURL(c *echo.Context, settings *models.Settings) string {
	if settings.PublicBaseURL != "" {
		return strings.TrimRight(settings.PublicBaseURL, "/")
	}
	return c.Scheme() + "://" + c.Request().Host
}

// --------------------------------------------------------------------------
//
// # Email templates
//
// --------------------------------------------------------------------------

type resetEmailData struct {
	Link       string
	Code       string
	TTLMinutes int
}

var resetEmailTmpl = template.Must(template.New("reset").Parse(`
<p>We received a request to reset the password for your Factum account.</p>
<p><a href="{{.Link}}">Click here to reset your password</a></p>
<p>Or enter this code on the password reset page: <strong>{{.Code}}</strong></p>
<p>This link and code expire in {{.TTLMinutes}} minutes and can each only be used once. If you didn't request this, you can safely ignore this email.</p>
`))

var ldapManagedEmailTmpl = template.Must(template.New("ldap-managed").Parse(`
<p>We received a request to reset the password for your Factum account.</p>
<p>Your account's password is managed by your organization's directory service (LDAP/Active Directory), not by Factum directly, so it can't be reset from here. Please contact your administrator.</p>
`))

func renderTemplate(tmpl *template.Template, data any) (string, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// --------------------------------------------------------------------------
//
// # POST /api/forgot-password
//
// --------------------------------------------------------------------------

type ForgotPasswordRequest struct {
	Email string `json:"email"`
}

// ApiForgotPassword always responds 200 {"ok":true} regardless of whether
// the email matches an account, whether that account can actually be
// reset, or whether sending the email succeeded - anything else would let
// a caller enumerate valid accounts by probing this endpoint.
func (ctrl *Controller) ApiForgotPassword(c *echo.Context) error {
	var req ForgotPasswordRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]any{"error": err.Error()})
	}
	email := strings.TrimSpace(req.Email)
	if email != "" {
		ctrl.sendPasswordResetEmailIfEligible(c, email)
	}
	return c.JSON(http.StatusOK, map[string]any{"ok": true})
}

func (ctrl *Controller) sendPasswordResetEmailIfEligible(c *echo.Context, email string) {
	settings, err := util.GetOrCreateSettings(ctrl.DB)
	if err != nil {
		slog.Error("forgot-password: failed to load settings", "error", err)
		return
	}

	var user models.User
	if err := ctrl.DB.Where("LOWER(email) = LOWER(?)", email).First(&user).Error; err != nil {
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			slog.Error("forgot-password: failed to look up user by email", "error", err)
			return
		}
		// No local row yet - for an LDAP user who has never logged in,
		// that's expected (a local row is normally only auto-provisioned
		// on first successful login, see web.authenticateNewLDAPUser).
		// Search the directory by email and provision one now instead of
		// silently giving up, so this flow isn't only reachable after a
		// first login.
		provisioned, err := ctrl.provisionLDAPUserByEmail(settings, email)
		if err != nil {
			slog.Error("forgot-password: ldap email lookup failed", "error", err)
			return
		}
		if provisioned == nil {
			return
		}
		user = *provisioned
	}

	if user.PasswordHash == ldapSentinelPassword && !ldapWritebackAvailable(settings) {
		body, err := renderTemplate(ldapManagedEmailTmpl, nil)
		if err != nil {
			slog.Error("forgot-password: failed to render ldap-managed notice", "error", err)
			return
		}
		if err := mail.Send(util.NewCommonConfig(settings), settings.EmailSender, user.Email, "About your Factum password", body); err != nil {
			slog.Error("forgot-password: failed to send ldap-managed notice", "error", err, "user", user.Username)
		}
		return
	}

	// Cooldown: skip creating a new token if the last one for this user is
	// very recent - guards against double-submit/trivial spam without
	// needing any new rate-limiting infrastructure.
	var recent models.PasswordResetToken
	cooldownCutoff := time.Now().Add(-passwordResetCooldown)
	if err := ctrl.DB.Where("user_id = ? AND created_at > ?", user.ID, cooldownCutoff).
		Order("created_at DESC").First(&recent).Error; err == nil {
		return
	}

	// A new request invalidates any still-active token, so an old
	// link/code stops working once a new one is issued.
	now := time.Now()
	ctrl.DB.Model(&models.PasswordResetToken{}).
		Where("user_id = ? AND consumed_at IS NULL", user.ID).
		Update("consumed_at", &now)

	rawToken, err := generateResetToken()
	if err != nil {
		slog.Error("forgot-password: failed to generate token", "error", err)
		return
	}
	rawCode, err := generateResetCode()
	if err != nil {
		slog.Error("forgot-password: failed to generate code", "error", err)
		return
	}

	prt := models.PasswordResetToken{
		UserID:    user.ID,
		TokenHash: hashToken(rawToken),
		CodeHash:  hashToken(rawCode),
		ExpiresAt: now.Add(passwordResetTokenTTL),
	}
	if err := ctrl.DB.Create(&prt).Error; err != nil {
		slog.Error("forgot-password: failed to store reset token", "error", err)
		return
	}

	link := fmt.Sprintf("%s/reset-password?token=%s", publicBaseURL(c, settings), rawToken)
	body, err := renderTemplate(resetEmailTmpl, resetEmailData{
		Link:       link,
		Code:       rawCode,
		TTLMinutes: int(passwordResetTokenTTL / time.Minute),
	})
	if err != nil {
		slog.Error("forgot-password: failed to render email", "error", err)
		return
	}
	if err := mail.Send(util.NewCommonConfig(settings), settings.EmailSender, user.Email, "Reset your Factum password", body); err != nil {
		slog.Error("forgot-password: failed to send email", "error", err, "user", user.Username)
	}
}

// --------------------------------------------------------------------------
//
// # POST /api/reset-password
//
// --------------------------------------------------------------------------

type ResetPasswordRequest struct {
	Token       string `json:"token,omitempty"`
	Email       string `json:"email,omitempty"`
	Code        string `json:"code,omitempty"`
	NewPassword string `json:"new_password"`
}

var errInvalidResetToken = fmt.Errorf("this reset link or code is invalid or has expired")

func (ctrl *Controller) ApiResetPassword(c *echo.Context) error {
	var req ResetPasswordRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]any{"error": err.Error()})
	}
	if len(req.NewPassword) < minPasswordLength {
		return c.JSON(http.StatusBadRequest, map[string]any{"error": fmt.Sprintf("password must be at least %d characters", minPasswordLength)})
	}

	prt, user, err := ctrl.resolveResetToken(req)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]any{"error": err.Error()})
	}

	settings, err := util.GetOrCreateSettings(ctrl.DB)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	if user.PasswordHash == ldapSentinelPassword {
		if !ldapWritebackAvailable(settings) {
			ctrl.consumeResetToken(prt)
			return c.JSON(http.StatusBadRequest, map[string]any{"error": "Your password is managed by your organization's directory service; contact your administrator."})
		}
		wb := ldapauth.WritebackConfig{
			BindDN:   util.Config.LdapWriteback.BindDN,
			Password: util.Config.LdapWriteback.Password,
		}
		if err := ldapauth.ChangePassword(ldapauth.ConfigFromSettings(settings), wb, user.Username, req.NewPassword); err != nil {
			slog.Error("reset-password: ldap write-back failed", "error", err, "user", user.Username)
			return c.JSON(http.StatusInternalServerError, map[string]any{"error": "failed to update password in the directory"})
		}
	} else {
		hash, err := HashPassword(req.NewPassword)
		if err != nil {
			return c.JSON(http.StatusInternalServerError, map[string]any{"error": "failed to hash password"})
		}
		user.PasswordHash = hash
		if err := ctrl.DB.Save(&user).Error; err != nil {
			return c.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
		}
	}

	ctrl.consumeResetToken(prt)
	return c.JSON(http.StatusOK, map[string]any{"ok": true})
}

// resolveResetToken finds the PasswordResetToken + target User a request
// redeems, via either the link token (direct hash lookup) or email+code
// (user lookup by email, then a constant-time hash compare against that
// user's latest active token, counting failed attempts). Any failure -
// unknown email, no active token, wrong code, expired, already consumed,
// too many attempts - collapses to the same errInvalidResetToken so a
// caller can't distinguish "wrong code" from "no such account".
func (ctrl *Controller) resolveResetToken(req ResetPasswordRequest) (*models.PasswordResetToken, models.User, error) {
	if req.Token != "" {
		var prt models.PasswordResetToken
		if err := ctrl.DB.Where("token_hash = ? AND consumed_at IS NULL AND expires_at > ?", hashToken(req.Token), time.Now()).
			First(&prt).Error; err != nil {
			return nil, models.User{}, errInvalidResetToken
		}
		var user models.User
		if err := ctrl.DB.First(&user, prt.UserID).Error; err != nil {
			return nil, models.User{}, errInvalidResetToken
		}
		return &prt, user, nil
	}

	email := strings.TrimSpace(req.Email)
	if email == "" || req.Code == "" {
		return nil, models.User{}, errInvalidResetToken
	}
	var user models.User
	if err := ctrl.DB.Where("LOWER(email) = LOWER(?)", email).First(&user).Error; err != nil {
		return nil, models.User{}, errInvalidResetToken
	}
	var prt models.PasswordResetToken
	if err := ctrl.DB.Where("user_id = ? AND consumed_at IS NULL AND expires_at > ?", user.ID, time.Now()).
		Order("created_at DESC").First(&prt).Error; err != nil {
		return nil, models.User{}, errInvalidResetToken
	}
	if prt.Attempts >= passwordResetMaxCodeAttempts {
		ctrl.consumeResetToken(&prt)
		return nil, models.User{}, errInvalidResetToken
	}
	if subtle.ConstantTimeCompare([]byte(hashToken(req.Code)), []byte(prt.CodeHash)) != 1 {
		ctrl.DB.Model(&prt).Update("attempts", prt.Attempts+1)
		return nil, models.User{}, errInvalidResetToken
	}
	return &prt, user, nil
}

func (ctrl *Controller) consumeResetToken(prt *models.PasswordResetToken) {
	now := time.Now()
	ctrl.DB.Model(prt).Update("consumed_at", &now)
}
